service: empowerex-finance

useDotenv: true

provider:
    name: aws
    runtime: nodejs22.x
    stage: ${opt:stage, 'dev'}
    region: ap-southeast-1
    architecture: x86_64
    httpApi:
        cors:
            allowedOrigins: ["*"]
            allowedHeaders: ["Content-Type", "Authorization"]
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            maxAge: 300
    environment:
        DYNAMODB_TABLE_NAME: EmpowerexFinance${self:provider.stage}
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                      - dynamodb:BatchWriteItem
                      - dynamodb:BatchGetItem
                  Resource:
                      - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/EmpowerexFinance${self:provider.stage}
                      - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/EmpowerexFinance${self:provider.stage}/index/*

custom:
    dynamodbTableName: EmpowerexFinance${self:provider.stage}

plugins:
    - serverless-offline
    - serverless-dynamodb-local

functions:
    # Offices
    createOffice:
        handler: src/api/offices/createOffice.handler
        events:
            - httpApi:
                  path: /offices
                  method: POST

    getOffices:
        handler: src/api/offices/getOffices.handler
        events:
            - httpApi:
                  path: /offices
                  method: GET

    getOfficeById:
        handler: src/api/offices/getOfficeById.handler
        events:
            - httpApi:
                  path: /offices/{officeId}
                  method: GET

    deleteOffice:
        handler: src/api/offices/deleteOffice.handler
        events:
            - httpApi:
                  path: /offices/{officeId}
                  method: DELETE

    patchOffice:
        handler: src/api/offices/patchOffice.handler
        events:
            - httpApi:
                  path: /offices/{officeId}
                  method: PATCH

    # PAP
    getPAPByOffice:
        handler: src/api/pap/getPAPByOffice.handler
        events:
            - httpApi:
                  path: /offices/{officeId}/paps
                  method: GET

    attachPAPToOffice:
        handler: src/api/pap/attachPAP.handler
        events:
            - httpApi:
                  path: /offices/{officeId}/paps
                  method: POST

    createPAP:
        handler: src/api/pap/createPAP.handler
        events:
            - httpApi:
                  path: /paps
                  method: POST

    getAllPAP:
        handler: src/api/pap/getAllPAP.handler
        events:
            - httpApi:
                  path: /paps
                  method: GET

    deletePAP:
        handler: src/api/pap/deletePAP.handler
        events:
            - httpApi:
                  path: /paps/{papId}
                  method: DELETE

    getPAPById:
        handler: src/api/pap/getPAPById.handler
        events:
            - httpApi:
                  path: /paps/{papId}
                  method: GET

    # UACS
    attachUACSToPAP:
        handler: src/api/uacs/attachUACS.handler
        events:
            - httpApi:
                  path: /offices/{officeId}/paps/{papId}/uacs
                  method: POST

    listUACSForPAP:
        handler: src/api/uacs/getUACS.handler
        events:
            - httpApi:
                  path: /offices/{officeId}/paps/{papId}/uacs
                  method: GET

    createUACS:
        handler: src/api/uacs/createUACS.handler
        events:
            - httpApi:
                  path: /uacs
                  method: POST

    deleteUACS:
        handler: src/api/uacs/deleteUACS.handler
        events:
            - httpApi:
                  path: /uacs/{uacsId}
                  method: DELETE

    getAllUACS:
        handler: src/api/uacs/getAllUACS.handler
        events:
            - httpApi:
                  path: /uacs
                  method: GET

    # Allotments
    createAllotmentItem:
        handler: src/api/allotments/createAllotmentItem.handler
        events:
            - httpApi:
                  path: /create-allotment-item
                  method: POST

    postAllotmentBreakdown:
        handler: src/api/allotments/postAllotmentBreakdown.handler
        events:
            - httpApi:
                  path: /create-allotment-breakdown
                  method: POST

    createAllotment:
        handler: src/api/allotments/createAllotment.handler
        events:
            - httpApi:
                  path: /allotment
                  method: POST

    getAllotmentsByOffice:
        handler: src/api/allotments/getAllotmentByOffice.handler
        memorySize: 256
        timeout: 10
        events:
            - httpApi:
                  path: /allotment
                  method: GET

    getAllotments:
        handler: src/api/allotments/filterAllotments.handler
        memorySize: 256 # mb
        timeout: 10 # seconds
        events:
            - httpApi:
                  path: /allotments
                  method: GET

    getAllotmentById:
        handler: src/api/allotments/getAllotmentById.handler
        memorySize: 256
        timeout: 10
        events:
            - httpApi:
                  path: /allotments/{allotmentId}
                  method: GET

    patchAllotmentDetails:
        handler: src/api/allotments/patchAllotmentDetails.handler
        events:
            - httpApi:
                  path: /allotments/{allotmentId}
                  method: PATCH

    updateAllotmentStatus:
        handler: src/api/allotments/updateAllotmentStatus.handler
        events:
            - httpApi:
                  path: /allotments/{allotmentId}/status
                  method: PATCH

    patchAllotmentBreakdown:
        handler: src/api/allotments/patchAllotmentBreakdown.handler
        events:
            - httpApi:
                  path: /allotments/{allotmentId}/breakdown
                  method: PATCH

    deleteAllotmentBreakdown:
        handler: src/api/allotments/deleteAllotmentBreakdown.handler
        events:
            - httpApi:
                  path: /allotments/delete-breakdown
                  method: POST

    assignOfficial:
        handler: src/api/exflow/assignOfficial.handler
        events:
            - httpApi:
                  path: /allotments/{allotmentId}/assign-official
                  method: POST

    updateExflowItem:
        handler: src/api/exflow/updateExflowItem.handler
        events:
            - httpApi:
                  path: /allotments/{allotmentId}/update-official
                  method: PATCH

#<====================== ALLOTMENT ======================>
resources:
    Resources:
        EmpowerexFinanceTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.dynamodbTableName}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: PK
                      AttributeType: S
                    - AttributeName: SK
                      AttributeType: S
                    - AttributeName: status
                      AttributeType: S
                    - AttributeName: papId
                      AttributeType: S
                    - AttributeName: allotmentId
                      AttributeType: S
                    - AttributeName: particulars
                      AttributeType: S
                    - AttributeName: createdAt
                      AttributeType: S
                KeySchema:
                    - AttributeName: PK
                      KeyType: HASH
                    - AttributeName: SK
                      KeyType: RANGE
                GlobalSecondaryIndexes:
                    - IndexName: StatusIndex
                      KeySchema:
                          - AttributeName: status
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL

                    - IndexName: AllotmentIdIndex
                      KeySchema:
                          - AttributeName: allotmentId
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL

                    - IndexName: PapIdIndex
                      KeySchema:
                          - AttributeName: papId
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL

                    - IndexName: ParticularsIndex
                      KeySchema:
                          - AttributeName: particulars
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL

                    - IndexName: StatusCreatedAtIndex
                      KeySchema:
                          - AttributeName: status
                            KeyType: HASH
                          - AttributeName: createdAt
                            KeyType: RANGE
                      Projection:
                          ProjectionType: ALL
                    - IndexName: MetadataIndex
                      KeySchema:
                          - AttributeName: SK
                            KeyType: HASH
                          - AttributeName: createdAt
                            KeyType: RANGE
                      Projection:
                          ProjectionType: ALL
