service: finance-allotment-api

# DO NOT REMOVE/DELETE THE COMMENTED LINES
provider:
  name: aws
  runtime: nodejs22.x
  stage: dev
  region: ap-southeast-1
  architecture: x86_64
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.allotmentsTable}

  # DO NOT REMOVE/DELETE THE COMMENTED LINES

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.allotmentsTable}

custom:
  allotmentsTable: Allotments
#   mainTableName: budget-db-${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  #<====================== ALLOTMENT ======================>
  getAllotmentsByOffice:
    handler: src/api/allotments/getAllotmentByOffice.handler
    name: get-allotments-by-office
    memorySize: 256 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: /allotments/office/{officeId}
          method: GET

  getAllAllotments:
    handler: src/api/allotments/getAllAllotments.handler
    name: get-all-alloments
    memorySize: 256 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: allotments
          method: GET

  createAllotment:
    handler: src/api/allotments/createAllotment.handler
    name: create-alloment
    memorySize: 256 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: allotments
          method: POST
  #<====================== ALLOTMENT ======================>

  #<======================= PAP ===========================>
  createPAP:
    handler: src/api/pap/createPAP.handler
    name: create-pap
    memorySize: 256 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: pap
          method: POST

  getPAPsbyAllotment:
    handler: src/api/pap/getPAPsByAllotment.handler
    name: get-paps-by-allotment
    memorySize: 256 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: /pap/by-allotment/{allotmentId}
          method: GET

  getPAP:
    handler: src/api/pap/getPAP.handler
    name: get-specific-pap-by-id
    memorySize: 256 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: /pap/{allotmentId}/{papId}
          method: GET
  #<======================= PAP ===========================>

  #<======================= UACS ==========================>
  createUACS:
    handler: src/api/uacs/createUACS.handler
    name: post-uacs-to-pap
    memorySize: 256 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: /uacs/{papId}
          method: POST

  getUACSbyPAP:
    handler: src/api/uacs/getUACSbyPAP.handler
    name: get-uacs-by-pap
    memorySize: 256 # mb
    timeout: 10 # seconds
    events:
      - http:
          path: /uacs/by-pap/{papId}
          method: GET

  #<======================= UACS ==========================>
# DO NOT REMOVE/DELETE THE COMMENTED LINES
resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.allotmentsTable}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
